version: '3.8'
services:
  sql_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass1_
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql    
    networks:
      - customnetwork

volumes:
  db:
    driver: local

networks:
  customnetwork:
    name: docker_network